-- Parametri runtime (es. stop forzato per leggi_libri_complete_manager).

CREATE TABLE IF NOT EXISTS public."GAL_PARAMETER" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL UNIQUE,
    valore_str text,
    valore_num integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS gal_parameter_nome_idx ON public."GAL_PARAMETER" (nome);

INSERT INTO public."GAL_PARAMETER" (nome, valore_str, valore_num)
VALUES ('LEGGI_LIBRI_COMP', NULL, 1)
ON CONFLICT (nome) DO NOTHING;

ALTER TABLE public."GAL_PARAMETER" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "dev_select" ON public."GAL_PARAMETER" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "dev_insert" ON public."GAL_PARAMETER" FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "dev_update" ON public."GAL_PARAMETER" FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "dev_delete" ON public."GAL_PARAMETER" FOR DELETE TO anon, authenticated USING (true);
